packages:
  - "packages/*"

allowBuilds:
  "@deepseek-ai/dsh-subprocess-local": false
  "@google/genai": false
  '@vscode/vsce-sign': true
  esbuild: false
  keytar: true
  koffi: false
  node-pty: false
  protobufjs: false
  sharp: true
