export const en = {
  composerMessage: "Message",
  settingsTitle: "Settings",
  closeSettings: "Close settings",
  settingsSections: "Settings sections",
  general: "General",
  models: "Models",
  plugins: "Plugins",
  agentPresets: "Agent Presets",
  extension: "Extension",
  loading: "Loading settings…",
  refreshing: "Refreshing settings…",
  retry: "Retry",
  unavailable: "Unavailable",
  disconnected: "DSH is disconnected. Cached settings remain visible.",
  restartRequired: "Restart DSH to apply all changes.",
  restartDsh: "Restart DSH",
  save: "Save",
  apply: "Apply",
  discard: "Discard",
  reset: "Reset",
  cancel: "Cancel",
  delete: "Delete",
  copy: "Copy",
  open: "Open",
  reveal: "Reveal",
  confirm: "Confirm",
  closeDirtyTitle: "Discard unsaved settings?",
  closeDirtyDetail: "Your unsaved changes will be lost.",
  conflictTitle: "Settings changed elsewhere",
  conflictDetail: "Review the latest values, then retry or discard your changes.",
  generalDefaultPreset: "Default agent preset",
  generalPermission: "Default permission",
  generalLanguage: "Language",
  generalAppearance: "Appearance",
  generalBusyEnter: "Enter while DSH is busy",
  languageSystem: "System default",
  languageEnglish: "English",
  languageChinese: "Chinese",
  appearanceSystem: "Follow DSH system preference",
  appearanceLight: "Light",
  appearanceDark: "Dark",
  editorThemeNote: "The extension follows the VS Code or Cursor theme.",
  busyEnterDescription: "Busy only; Cmd/Ctrl+Enter uses the other behavior.",
  busyEnterQueue: "Queue",
  busyEnterSteer: "Steer",
  unknownLocale: "Unknown locale",
  modelsAddProvider: "Add provider",
  modelsProvider: "Provider",
  modelsBaseUrl: "Base URL",
  modelsCredential: "Credential",
  modelsCredentialConfigured: "Credential configured",
  modelsCredentialMissing: "Credential not configured",
  modelsReplaceCredential: "Replace credential",
  modelsRemoveCredential: "Remove credential",
  modelsCatalogUnavailable: "Model catalog unavailable",
  modelsAddCustomProvider: "Add a custom provider",
  modelsCustomTitle: "Custom provider",
  modelsCustomRoute: "Provider ID",
  modelsCustomRouteHint: "Use lowercase letters, numbers, and single hyphens; start with a letter.",
  modelsCustomRouteInvalid: "This provider ID has an invalid format.",
  modelsCustomRouteTaken: "This provider ID is already in use.",
  modelsCustomDisplayName: "Display name",
  modelsCustomApi: "API protocol",
  modelsCustomNeedsBaseUrl: "Enter a base URL.",
  modelsCustomNeedsModels: "Add at least one valid model.",
  modelsCreate: "Create",
  modelsCreating: "Creating…",
  modelsRoute: "Route",
  modelsRouteActive: "active",
  modelsRouteDormant: "dormant",
  modelsRouteCustom: "custom",
  modelsRouteCatalog: "catalog",
  modelsCatalog: "Catalog",
  modelsCatalogReady: "ready",
  modelsCatalogDormant: "dormant",
  modelsUseProviderDefault: "Use provider default",
  modelsResetModels: "Reset models",
  modelsModelId: "Model ID",
  modelsModelName: "Model name",
  modelsContextWindow: "Context window",
  modelsMaxTokens: "Max tokens",
  modelsRemoveModel: "Remove model",
  modelsAddModel: "Add model",
  modelsApiKey: "API key",
  modelsApiKeyBlankNew: "Leave the API key empty or enter a non-blank value.",
  modelsApiKeyIllegal: "Paste the key value only, without quotes, spaces, or an environment assignment.",
  modelsEdit: "Edit",
  modelsActive: "Active",
  modelsDormant: "Dormant",
  modelsCatalogReadyLabel: "Catalog ready",
  modelsCatalogDormantLabel: "Catalog dormant",
  modelsDeleteTitle: "Delete provider?",
  modelsDeleteDetail: "This removes the user provider profile. A writable page-managed credential is removed first.",
  modelsValidationList: "Models must be a list.",
  modelsValidationId: "Model {index} requires an ID.",
  modelsValidationDuplicate: "Model {index} duplicates ID “{id}”.",
  modelsValidationName: "Model {index} name must be non-empty text.",
  modelsValidationContext: "Model {index} context window must be a positive integer.",
  modelsValidationMaxTokens: "Model {index} max tokens must be a positive integer.",
  modelsValidationText: "{field} must be text.",
  modelsValidationNumber: "{field} must be a number.",
  modelsValidationMin: "{field} must be at least {min}.",
  modelsValidationMax: "{field} must be at most {max}.",
  modelsValidationWhole: "{field} must be a whole number.",
  modelsValidationUnsupported: "{field} is not supported.",
  modelsValidationBaseUrl: "Base URL must be an absolute HTTP or HTTPS URL.",
  modelsCredentialStage: "Credential",
  modelsSettingsStage: "Settings",
  modelsCredentialRemovalStage: "Credential removal",
  modelsProviderRemovalStage: "Provider removal",
  modelsProviderRemovalCredentialGone: "Provider removal failed after its credential was removed. Re-enter the credential if the provider remains.",
  modelsSecretReenterApply: "Re-enter the cleared secret and apply again.",
  modelsSecretReenterCreate: "Re-enter the cleared secret and create again.",
  pluginsConfigurable: "Configurable",
  pluginsAll: "All",
  pluginsInventory: "Plugin inventory",
  pluginsEnabled: "Enabled",
  pluginsDisabled: "Disabled",
  pluginsPhase: "Runtime phase",
  pluginsEmptyConfigurable: "No configurable plugins.",
  pluginsApiKey: "API key",
  pluginsCredentialConfigured: "Credential configured",
  pluginsCredentialMissing: "Credential not configured",
  pluginsNamespace: "Plugin namespace",
  pluginsRemoveCredential: "Remove configured credential",
  pluginsReadOnlyDirty: "Discard read-only settings edits to save the credential separately.",
  pluginsValidationBaseUrl: "Base URL must be blank or an absolute HTTP or HTTPS URL.",
  pluginsValidationPositive: "Enter a positive number. Integer fields require a whole number.",
  pluginsStale: "This plugin changed elsewhere. Saving uses the refreshed revision.",
  pluginsSecretReenter: "Settings were saved, but the credential was not. Re-enter the API key and save again.",
  presetsDefault: "Default",
  presetsSystem: "Built in",
  presetsUser: "User",
  presetsCopyTitle: "Copy Agent Preset",
  presetsDeleteTitle: "Delete Agent Preset",
  presetsName: "Name",
  presetsId: "Identifier",
  presetsIntro: "A preset defines the tools, prompt, and capabilities used by new sessions.",
  presetsBuiltInGroup: "Built in",
  presetsUserGroup: "User",
  presetsNoDescription: "No description.",
  presetsBroken: "Failed to load",
  presetsSetDefault: "Set {name} as default",
  presetsView: "View",
  presetsOpen: "Open {name}",
  presetsCopy: "Copy {name}",
  presetsDelete: "Delete {name}",
  presetsCopyIntro: "Copy this preset on this machine. The identifier becomes its directory name.",
  presetsIdInvalid: "Use lowercase letters, digits, and hyphens, starting with a letter or digit.",
  presetsIdTaken: "A preset with this identifier already exists.",
  presetsCreate: "Create",
  presetsCreating: "Creating…",
  presetsViewerTitle: "Preset content · {name}",
  presetsDeleteDetail: "This permanently deletes the user preset directory. Running sessions keep their existing composition.",
  presetsDeleteFallbackDetail: "Choose another available default first. The default change and deletion are separate operations.",
  presetsFallback: "Replacement default",
  presetsDefaultChangedDeleteFailed: "The default changed, but deletion failed. Retry deletes only the preset.",
  presetsOpening: "Opening preset folder…",
  presetsEmpty: "No Agent Presets are available.",
  extensionBinaryPath: "DSH binary path",
  extensionBinaryPathHint: "Leave empty to probe common install locations and PATH automatically.",
  extensionHandshakeTimeout: "Handshake timeout (ms)",
  extensionOpenEditorSettings: "Open VS Code Settings",
  extensionOpenDocument: "Open DSH settings document",
  extensionRevealHome: "Reveal DSH home",
  extensionActionPending: "Extension action in progress…",
  validationRequired: "This value is required.",
  validationInteger: "Enter a whole number.",
  validationTimeout: "Enter a value from 1,000 to 300,000.",
  readOnly: "Read only",
  overridden: "Overridden",
  liveApply: "Applies immediately",
  restartApply: "Requires restart",
  noResults: "No settings found.",
  operationFailed: "The operation failed.",
} as const;
