import type { en } from "./en.js";

export const zh: Record<keyof typeof en, string> = {
  composerMessage: "消息",
  settingsTitle: "设置",
  closeSettings: "关闭设置",
  settingsSections: "设置分区",
  general: "常规",
  models: "模型",
  plugins: "插件",
  agentPresets: "智能体预设",
  extension: "扩展",
  loading: "正在加载设置…",
  refreshing: "正在刷新设置…",
  retry: "重试",
  unavailable: "不可用",
  disconnected: "DSH 已断开连接。缓存的设置仍然可见。",
  restartRequired: "请重启 DSH 以应用全部更改。",
  restartDsh: "重启 DSH",
  save: "保存",
  apply: "应用",
  discard: "放弃",
  reset: "重置",
  cancel: "取消",
  delete: "删除",
  copy: "复制",
  open: "打开",
  reveal: "在文件管理器中显示",
  confirm: "确认",
  closeDirtyTitle: "放弃未保存的设置？",
  closeDirtyDetail: "未保存的更改将会丢失。",
  conflictTitle: "设置已在其他位置更改",
  conflictDetail: "请查看最新值，然后重试或放弃更改。",
  generalDefaultPreset: "默认智能体预设",
  generalPermission: "默认权限",
  generalLanguage: "语言",
  generalAppearance: "外观",
  generalBusyEnter: "DSH 忙碌时按 Enter",
  languageSystem: "系统默认",
  languageEnglish: "英语",
  languageChinese: "中文",
  appearanceSystem: "跟随 DSH 系统偏好",
  appearanceLight: "浅色",
  appearanceDark: "深色",
  editorThemeNote: "扩展会跟随 VS Code 或 Cursor 主题。",
  busyEnterDescription: "仅在智能体运行时生效；Cmd/Ctrl+Enter 使用另一行为。",
  busyEnterQueue: "排队发送",
  busyEnterSteer: "插话发送",
  unknownLocale: "未知语言",
  modelsAddProvider: "添加提供商",
  modelsProvider: "提供商",
  modelsBaseUrl: "基础 URL",
  modelsCredential: "凭据",
  modelsCredentialConfigured: "凭据已配置",
  modelsCredentialMissing: "凭据未配置",
  modelsReplaceCredential: "替换凭据",
  modelsRemoveCredential: "移除凭据",
  modelsCatalogUnavailable: "模型目录不可用",
  modelsAddCustomProvider: "添加自定义提供商",
  modelsCustomTitle: "自定义提供商",
  modelsCustomRoute: "提供商标识",
  modelsCustomRouteHint: "使用小写字母、数字和单个连字符，并以字母开头。",
  modelsCustomRouteInvalid: "此提供商标识格式无效。",
  modelsCustomRouteTaken: "此提供商标识已被使用。",
  modelsCustomDisplayName: "显示名称",
  modelsCustomApi: "API 协议",
  modelsCustomNeedsBaseUrl: "请输入基础 URL。",
  modelsCustomNeedsModels: "请至少添加一个有效模型。",
  modelsCreate: "创建",
  modelsCreating: "正在创建…",
  modelsRoute: "路由",
  modelsRouteActive: "已启用",
  modelsRouteDormant: "休眠",
  modelsRouteCustom: "自定义",
  modelsRouteCatalog: "目录内",
  modelsCatalog: "目录",
  modelsCatalogReady: "就绪",
  modelsCatalogDormant: "休眠",
  modelsUseProviderDefault: "使用提供商默认值",
  modelsResetModels: "重置模型",
  modelsModelId: "模型标识",
  modelsModelName: "模型名称",
  modelsContextWindow: "上下文窗口",
  modelsMaxTokens: "最大输出",
  modelsRemoveModel: "移除模型",
  modelsAddModel: "添加模型",
  modelsApiKey: "API 密钥",
  modelsApiKeyBlankNew: "将 API 密钥留空，或输入非空白值。",
  modelsApiKeyIllegal: "仅粘贴密钥值，不要包含引号、空格或环境变量赋值。",
  modelsEdit: "编辑",
  modelsActive: "已启用",
  modelsDormant: "休眠",
  modelsCatalogReadyLabel: "目录就绪",
  modelsCatalogDormantLabel: "目录休眠",
  modelsDeleteTitle: "删除提供商？",
  modelsDeleteDetail: "这会移除用户提供商配置。可写且由此页面管理的凭据会先被移除。",
  modelsValidationList: "模型必须是列表。",
  modelsValidationId: "模型 {index} 需要标识。",
  modelsValidationDuplicate: "模型 {index} 与标识“{id}”重复。",
  modelsValidationName: "模型 {index} 的名称必须是非空文本。",
  modelsValidationContext: "模型 {index} 的上下文窗口必须是正整数。",
  modelsValidationMaxTokens: "模型 {index} 的最大输出必须是正整数。",
  modelsValidationText: "{field} 必须是文本。",
  modelsValidationNumber: "{field} 必须是数字。",
  modelsValidationMin: "{field} 必须至少为 {min}。",
  modelsValidationMax: "{field} 必须至多为 {max}。",
  modelsValidationWhole: "{field} 必须是整数。",
  modelsValidationUnsupported: "不支持 {field}。",
  modelsValidationBaseUrl: "基础 URL 必须是绝对 HTTP 或 HTTPS URL。",
  modelsCredentialStage: "凭据",
  modelsSettingsStage: "设置",
  modelsCredentialRemovalStage: "移除凭据",
  modelsProviderRemovalStage: "移除提供商",
  modelsProviderRemovalCredentialGone: "移除提供商失败，但其凭据已被移除。如果提供商仍存在，请重新输入凭据。",
  modelsSecretReenterApply: "请重新输入已清除的密钥，然后再次应用。",
  modelsSecretReenterCreate: "请重新输入已清除的密钥，然后再次创建。",
  pluginsConfigurable: "可配置",
  pluginsAll: "全部",
  pluginsInventory: "插件清单",
  pluginsEnabled: "已启用",
  pluginsDisabled: "已禁用",
  pluginsPhase: "运行阶段",
  pluginsEmptyConfigurable: "没有可配置的插件。",
  pluginsApiKey: "API 密钥",
  pluginsCredentialConfigured: "凭据已配置",
  pluginsCredentialMissing: "凭据未配置",
  pluginsNamespace: "插件命名空间",
  pluginsRemoveCredential: "移除已配置的凭据",
  pluginsReadOnlyDirty: "请放弃只读设置编辑，以单独保存凭据。",
  pluginsValidationBaseUrl: "基础 URL 必须留空或为绝对 HTTP 或 HTTPS URL。",
  pluginsValidationPositive: "请输入正数；整数字段必须为整数。",
  pluginsStale: "此插件已在其他位置更改。保存将使用刷新后的版本。",
  pluginsSecretReenter: "设置已保存，但凭据未保存。请重新输入 API 密钥并再次保存。",
  presetsDefault: "默认",
  presetsSystem: "内置",
  presetsUser: "用户",
  presetsCopyTitle: "复制智能体预设",
  presetsDeleteTitle: "删除智能体预设",
  presetsName: "名称",
  presetsId: "标识符",
  presetsIntro: "预设定义新会话使用的工具、提示词和能力。",
  presetsBuiltInGroup: "内置",
  presetsUserGroup: "用户",
  presetsNoDescription: "暂无描述。",
  presetsBroken: "加载失败",
  presetsSetDefault: "将 {name} 设为默认",
  presetsView: "查看",
  presetsOpen: "打开 {name}",
  presetsCopy: "复制 {name}",
  presetsDelete: "删除 {name}",
  presetsCopyIntro: "在本机复制此预设。标识符将成为其目录名。",
  presetsIdInvalid: "只能使用小写字母、数字与连字符，且以字母或数字开头。",
  presetsIdTaken: "该标识符已被占用。",
  presetsCreate: "创建",
  presetsCreating: "正在创建…",
  presetsViewerTitle: "预设内容 · {name}",
  presetsDeleteDetail: "这会永久删除用户预设目录。运行中的会话保持现有组装。",
  presetsDeleteFallbackDetail: "请先选择另一个可用默认预设。更改默认值和删除是两个独立操作。",
  presetsFallback: "替代默认预设",
  presetsDefaultChangedDeleteFailed: "默认预设已更改，但删除失败。重试只会删除该预设。",
  presetsOpening: "正在打开预设目录…",
  presetsEmpty: "没有可用的智能体预设。",
  extensionBinaryPath: "DSH 二进制文件路径",
  extensionBinaryPathHint: "留空可自动探测常见安装位置和 PATH。",
  extensionHandshakeTimeout: "握手超时（毫秒）",
  extensionOpenEditorSettings: "打开 VS Code 设置",
  extensionOpenDocument: "打开 DSH 设置文档",
  extensionRevealHome: "显示 DSH 主目录",
  extensionActionPending: "正在执行扩展操作…",
  validationRequired: "此值为必填项。",
  validationInteger: "请输入整数。",
  validationTimeout: "请输入 1,000 到 300,000 之间的值。",
  readOnly: "只读",
  overridden: "已覆盖",
  liveApply: "立即应用",
  restartApply: "需要重启",
  noResults: "未找到设置。",
  operationFailed: "操作失败。",
};
